apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- services.yaml
- analysis.yaml
- alerts.yaml
- sealed-secret.yaml
- servicemonitor.yaml
configMapGenerator:
- behavior: create
  literals:
  - VERSION="prod-1.0.0"
  - ENVIRONMENT="production"
  name: app-config
generatorOptions:
  disableNameSuffixHash: true
patches:
- path: patches.yaml
images:
- name: prometheus-canary-demo-placeholder
  newName: manhcuong139/prometheus-canary-demo
  newTag: 49297089ddf6a0de83f8bbc7e2f2f20d0df17c69
