---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: default
spec:
  encryptedData:
    DATABASE_PASSWORD: AgBkl0N+NvD0ccivQRBDp9upuXKWXEv1tbO+/ZwLq6C836QDxYiFWf+bP7RrD8bvAFdH5MEIzmdw8K+NTag3HZiW7P07opWZ36kbbx1HIWd+d+tT+LGBlc6bD6BLo1VIwwTl/yJozEVHoxF40sakuwgdT8iY9p37mrlBg0iSf27s2GjlRtJ2fKHe8TW1UPwUlSY3jkMmJxYoe91IyrQyfFbBX3CWfuDPH5ylMk3IFiC47juhOCWqPSCxQ2zw4Ew3GZmW1bVI0ZXkNv2JQ/TyBAS9rrgSg4ElNnJmCP01tJ3aGyesz7tfeYPjAyqQrylq+KFARnL06oGGpdpV2pClw/2OTocS85392UkvckjaGUEaMpM4fsXMMfwjugAXNrYfuZdrGXmb5cNFQut1ZTve75obHwbaQo+MaDNVz2J9jRJoirhhyrqSE6glN++8+Pc0bx6uCqAYoXW2Ge3vRbdD0m0hb2blQ7W6Nq/bedlEyC6HCri2ahlUAJBj8NQyiVas6VOP2tqLEZWmG9dK1XNN9U7NDDpo7d5njWrq1r6ITrg/z2VwM3JIbEWxMC6qoGi6uvDnjkTYwaGNGhjFLXGjk3XOB5dsnmkYrASBBSzPWORPeydG1Wox7HYQ5d9jBvr3fY0jkte2yhxlr5qWtqhu/m2LMJgmjaUbe58vmU8I7Vmx1CGmISvqG07wdu+2NmL6GnkNHg5Uz8qa9NjY2nmeleuOT3R2wwoAnALuhQImdjaSBA==
  template:
    metadata:
      name: db-secret
      namespace: default
    type: Opaque
