---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: prod
spec:
  encryptedData:
    DATABASE_PASSWORD: AgC00EPAR4qIpCn29HTrKavjrfwtcQXPjmPAQ/vJ8/SoIH33CWUoHZbvQOW/HWhReP3+bc9dv8TLfFxx4Lh+S8rQQOMcFTRa6vfvc3ykzfL5yFg6ZWX58whpQsq6Lf4qOrJQgRKbVdeaVvEZtEeeatoHQRR+9cLnKacApp3YfsCD9ao1OpxeKvwtlsF4Gl3bUvUgiH3q0nA2FSHcHrzp4HZvswP654kMZvSc66XcEwJfOhWBTUM+bMMbxu+A8Bfo0aG+cWSjkc04n7x5nOcR4y9QtIMsz4IFMy2/q/XMRBlZgZ+hcsgSqSVyCHXyMM6ifLzWKZ+pkM2TPGFhj6uxmyfUXLFqcl0gd/SA4bl+Lei8avujwAbHGxDroC/jWGSxP4oUpzUVk+ZW8ZRcNph2ggZjeaTJ14fKWy2sCBvqtLaLUPIz25P28rBSqyOGrfXTVR4zixCum4+1DA+wXOsiqOt/mRtjDdpNHOnRiijp4ox6BVKDZRbbzRGfzrWzY+2Nfhz1h3oVmkmwcyFGq+kFJp7MtnBL7TCdFkl/OpeVExMRuJ7QFbgOtCPO9n2myUsyGKN9WaWzPK3V/hUpYa3CFyy0+Ku0Gm4RZiPO8kL9rp9opEviDTaeOr1Tgb2Oe/bZkPvvtlzZTGlTYWoIHuQZi5gYGh4w4mJcx8C4LmIrNB3qxK8gN1HWMUZuIhhapi0RlF06aVpwDIevJbhY/US6rF62w8sjmkXrpJ102fltf14fgw==
  template:
    metadata:
      name: db-secret
      namespace: prod
    type: Opaque
