apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
# Tự động sinh ConfigMap cho Dev
configMapGenerator:
  - name: app-config
    behavior: create
    literals:
      - VERSION="dev-1.0.0"
      - ENVIRONMENT="dev"
generatorOptions:
  disableNameHash: true
patches:
- path: patches.yaml
images:
- name: prometheus-canary-demo-placeholder
  newName: manhcuong139/prometheus-canary-demo
  newTag: 06fa47bbde963fa998bfbfb12bcceb1deddfff74
